export const FETCH_COMPANYS_REQUEST = "FETCH_COMPANYS_REQUEST";
export const FETCH_COMPANYS_SUCCESS = "FETCH_COMPANYS_SUCCESS";
export const FETCH_COMPANYS_FAILURE = "FETCH_COMPANYS_FAILURE";
export const SEARCH_COMPANYS_SUCCESS = "SEARCH_COMPANYS_SUCCESS ";
